### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by gregid** [ThiagoCComelli/JS2SHACL-JSON-Schema-to-SHACL-conversor#4]
I couldn't find anywhere under which license the converter is being published. Would it be possible to have it licensed as `MIT` or similar type of license?

**Comment by ThiagoCComelli** [comment]
For now the project has no license. This conversion tool is a project of a scientific research that we are developing. I'm going to talk to my teacher-advisors and see what would be the best license for this project. (probably MIT)
